
name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: YairCx/ASTlab2
          cx_tenant: cx_gs_enablement
          base_uri: https://eu.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CLIENT }}
          cx_client_secret: ${{ secrets.SECRET }}
